# Generated by Django 5.1.3 on 2025-01-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='generated_proposal',
        ),
        migrations.AddField(
            model_name='project',
            name='frameworks',
            field=models.JSONField(default=list, help_text="List of frameworks or libraries used (e.g., ['Django', 'React'])"),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.JSONField(default=list, help_text="List of programming languages used (e.g., ['Python', 'JavaScript'])"),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
