# Generated by Django 5.1.3 on 2025-01-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.JSONField()),
                ('fixed_price', models.CharField(max_length=50)),
                ('est_budget', models.CharField(max_length=50)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
